
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Speakeasy.Models.Schemas
{
    using System;
using System.Net.Http;
using Newtonsoft.Json;
using Speakeasy.Utils;
    
    public class GetSchemaDiffRequest
    {
    /// <summary>
    /// The ID of the Api to retrieve schemas for.
    /// </summary>
        
        [JsonProperty("apiID")]
        public string ApiID { get; set; }
        
    /// <summary>
    /// The base revision ID of the schema to retrieve.
    /// </summary>
        
        [JsonProperty("baseRevisionID")]
        public string BaseRevisionID { get; set; }
        
    /// <summary>
    /// The target revision ID of the schema to retrieve.
    /// </summary>
        
        [JsonProperty("targetRevisionID")]
        public string TargetRevisionID { get; set; }
        
    /// <summary>
    /// The version ID of the Api to delete metadata for.
    /// </summary>
        
        [JsonProperty("versionID")]
        public string VersionID { get; set; }
        
        internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, GetSchemaDiffRequest value, string baseUrl)
        {
            if("getSchemaDiff" == operationId)
            {
                
                var apiID = PathParamSerializer.Serialize("simple", false, value.ApiID);
                
                var baseRevisionID = PathParamSerializer.Serialize("simple", false, value.BaseRevisionID);
                
                var targetRevisionID = PathParamSerializer.Serialize("simple", false, value.TargetRevisionID);
                
                var versionID = PathParamSerializer.Serialize("simple", false, value.VersionID);
                var message = new HttpRequestMessage(HttpMethod.Get, baseUrl + $"/v1/apis/{apiID}/version/{versionID}/schema/{baseRevisionID}/diff/{targetRevisionID}");
                return message;
            }
            throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [GetSchemaDiffRequest]");
        }
    }
}