//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: cd23dc91c63a
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Operations
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Utils;

    public class CreateRequest
    {
        /// <summary>
        /// URL to shorten.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; } = default!;
    }
}