//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: f37173a7d8d0
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Operations
{
    using SpeakeasySDK.Utils;

    public class GetAccessTokenRequest
    {
        /// <summary>
        /// The workspace ID.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=workspace_id")]
        public string WorkspaceId { get; set; } = default!;
    }
}