//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: a5a21e6a84fc
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Operations
{
    using SpeakeasySDK.Utils;

    public class GetPublishingTokenByIDRequest
    {
        /// <summary>
        /// Unique identifier of the publishing token.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=tokenID")]
        public string TokenID { get; set; } = default!;
    }
}