//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Operations
{
    using SpeakeasySDK.Utils;
    using System;
    
    public class GetWorkspaceTargetsRequest
    {

        /// <summary>
        /// Filter to only return targets with events created after this timestamp
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=after_last_event_created_at")]
        public DateTime? AfterLastEventCreatedAt { get; set; }
    }
}