//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: b7f3a50313ad
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Operations
{
    using SpeakeasySDK.Utils;

    public class IgnoreSubscriptionNamespaceRequest
    {
        /// <summary>
        /// The existing subscription ID.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscriptionID")]
        public string SubscriptionID { get; set; } = default!;

        /// <summary>
        /// The namespace name.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=namespaceName")]
        public string NamespaceName { get; set; } = default!;
    }
}