//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Operations
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Utils;
    
    /// <summary>
    /// Apply options
    /// </summary>
    public class ApplyOperationIDsRequestBody
    {

        /// <summary>
        /// Whether to apply the suggestions as an overlay or replace the existing operationIDs. Default: false
        /// </summary>
        [JsonProperty("as_overlay")]
        public bool? AsOverlay { get; set; }
    }
}