//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Operations
{
    using SpeakeasySDK.Utils;
    
    public class GetWorkspaceRequest
    {

        /// <summary>
        /// Unique identifier of the workspace.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspaceID")]
        public string? WorkspaceID { get; set; }
    }
}