//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Client.SDK.Models.Shared
{
    using Newtonsoft.Json;
    using Speakeasy.Client.SDK.Utils;
    
    /// <summary>
    /// Key-Value pairs associated with a request
    /// </summary>
    public class RequestMetadata
    {

        [JsonProperty("key")]
        public string? Key { get; set; }

        [JsonProperty("value")]
        public string? Value { get; set; }
    }
}