//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Client.SDK.Models.Operations
{
    using Newtonsoft.Json;
    using Speakeasy.Client.SDK.Utils;
    
    /// <summary>
    /// OK
    /// </summary>
    public class GetLintingReportSignedUrlSignedAccess
    {

        [JsonProperty("url")]
        public string Url { get; set; } = default!;
    }
}