//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Client.SDK.Models.Operations
{
    using Newtonsoft.Json;
    using Speakeasy.Client.SDK.Models.Operations;
    using Speakeasy.Client.SDK.Utils;
    
    public class Opts
    {

        [JsonProperty("depth_style")]
        public DepthStyle? DepthStyle { get; set; }

        [JsonProperty("style")]
        public Style? Style { get; set; }
    }
}