//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Client.SDK.Models.Operations
{
    using Speakeasy.Client.SDK.Models.Shared;
    using Speakeasy.Client.SDK.Utils;
    
    public class PostTagsRequest
    {

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=namespace_name")]
        public string NamespaceName { get; set; } = default!;

        /// <summary>
        /// A JSON representation of the tags to add
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public AddTags? AddTags { get; set; }
    }
}