//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.Client.SDK.Models.Operations
{
    using Speakeasy.Client.SDK.Utils;
    
    public class SearchWorkspaceEventsRequest
    {

        /// <summary>
        /// Unique identifier of the lint report digest.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=lint_report_digest")]
        public string? LintReportDigest { get; set; }

        /// <summary>
        /// Unique identifier of the openapi diff report digest.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=openapi_diff_report_digest")]
        public string? OpenapiDiffReportDigest { get; set; }

        /// <summary>
        /// Unique identifier of the source revision digest.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=source_revision_digest")]
        public string? SourceRevisionDigest { get; set; }

        /// <summary>
        /// Unique identifier of the workspace.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspaceID")]
        public string? WorkspaceID { get; set; }
    }
}