//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: 59e9dd136600
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Models.Shared;
    using SpeakeasySDK.Utils;
    using System;

    public class SchemaStoreItem
    {
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        [JsonProperty("format")]
        public Models.Shared.Format Format { get; set; } = default!;

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("packageName")]
        public string PackageName { get; set; } = default!;

        [JsonProperty("sdkClassname")]
        public string SDKClassname { get; set; } = default!;

        [JsonProperty("spec")]
        public string Spec { get; set; } = default!;
    }
}