//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Models.Shared;
    using SpeakeasySDK.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// A request to add workspace feature flags
    /// </summary>
    public class WorkspaceFeatureFlagRequest
    {

        [JsonProperty("feature_flags")]
        public List<WorkspaceFeatureFlag> FeatureFlags { get; set; } = default!;
    }
}