//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Utils;
    using System;
    
    /// <summary>
    /// A speakeasy workspace
    /// </summary>
    public class Workspace
    {

        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("organization_id")]
        public string OrganizationId { get; set; } = default!;

        [JsonProperty("slug")]
        public string Slug { get; set; } = default!;

        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; } = default!;

        [JsonProperty("verified")]
        public bool Verified { get; set; } = default!;

        [JsonProperty("inactive")]
        public bool? Inactive { get; set; }

        /// <summary>
        /// Deprecated. Use organization.telemetry_disabled instead.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("telemetry_disabled")]
        public bool? TelemetryDisabled { get; set; }
    }
}