//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Models.Shared;
    using SpeakeasySDK.Utils;
    
    /// <summary>
    /// A response for workspace user invite
    /// </summary>
    public class WorkspaceInviteResponse
    {

        [JsonProperty("invite_link")]
        public string? InviteLink { get; set; } = null;

        [JsonProperty("relationship")]
        public Relationship Relationship { get; set; } = default!;
    }
}