workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    speakeasy:
        inputs:
            - location: https://www.speakeasy.com/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/speakeasy
targets:
    speakeasy-client-sdk-csharp:
        target: csharp
        source: speakeasy
        publish:
            nuget:
                apiKey: $nuget_api_key
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/code-samples-csharp-speakeasy-client-sdk-csharp
