workflowVersion: 1.0.0
speakeasyVersion: 1.300.1
sources:
    speakeasy:
        inputs:
            - location: https://docs.speakeasyapi.dev/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/speakeasy
targets:
    speakeasy-client-sdk-csharp:
        target: csharp
        source: speakeasy
        publish:
            nuget:
                apiKey: $nuget_api_key
