workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    speakeasy:
        inputs:
            - location: https://docs.speakeasyapi.dev/openapi.yaml
targets:
    speakeasy-client-sdk-csharp:
        target: csharp
        source: speakeasy
        publish:
            nuget:
                apiKey: $nuget_api_key
