
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    
    public class AccessDetails
    {

        [JsonProperty("generation_allowed")]
        public bool GenerationAllowed { get; set; } = default!;

        [JsonProperty("level")]
        public Level? Level { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; } = default!;
    }
}