//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// A request to configure a GitHub repository for mintlify
    /// </summary>
    public class GithubConfigureMintlifyRepoRequest
    {

        /// <summary>
        /// The input OpenAPI document
        /// </summary>
        [JsonProperty("input")]
        public string Input { get; set; } = default!;

        /// <summary>
        /// The GitHub organization name
        /// </summary>
        [JsonProperty("org")]
        public string Org { get; set; } = default!;

        /// <summary>
        /// The overlays to apply
        /// </summary>
        [JsonProperty("overlays")]
        public List<string> Overlays { get; set; } = default!;

        /// <summary>
        /// The GitHub repository name
        /// </summary>
        [JsonProperty("repo")]
        public string Repo { get; set; } = default!;
    }
}