//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Utils;
    using System;
    
    /// <summary>
    /// A namespace contains many revisions.
    /// </summary>
    public class Namespace
    {

        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// {organization_slug}/{workspace_slug}/{namespace_name}
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// A human-readable name for the namespace.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; } = default!;
    }
}