//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Models.Shared;
    using SpeakeasySDK.Utils;
    using System;
    
    /// <summary>
    /// A speakeasy organization
    /// </summary>
    public class Organization
    {

        [JsonProperty("account_type")]
        public AccountType AccountType { get; set; } = default!;

        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        [JsonProperty("free_trial_expiry")]
        public DateTime? FreeTrialExpiry { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("slug")]
        public string? Slug { get; set; }

        [JsonProperty("telemetry_disabled")]
        public bool TelemetryDisabled { get; set; } = default!;

        [JsonProperty("updated_at")]
        public DateTime? UpdatedAt { get; set; }
    }
}