//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Shared
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Models.Shared;
    using SpeakeasySDK.Utils;
    
    /// <summary>
    /// A document referenced by a workflow
    /// </summary>
    public class WorkflowDocument
    {

        [JsonProperty("auth")]
        public Models.Shared.Auth? Auth { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; } = default!;
    }
}