
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SDK.Models.Shared
{
    using Newtonsoft.Json;
    
    public class SchemaDiffValueChange
    {
    /// <summary>
    /// Represents the previous value of the element.
    /// </summary>
        
        [JsonProperty("From")]
        public string From { get; set; }
        
    /// <summary>
    /// Represents the current value of the element.
    /// </summary>
        
        [JsonProperty("To")]
        public string To { get; set; }
        
    }
}