//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// @generated-id: be864506f870
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasySDK.Models.Errors
{
    using Newtonsoft.Json;
    using SpeakeasySDK.Utils;
    using System;
    using System.Net.Http;

    public class ErrorPayload
    {
        /// <summary>
        /// A developer-facing error message.
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; } = default!;

        /// <summary>
        /// The HTTP status code.
        /// </summary>
        [JsonProperty("status_code")]
        public int StatusCode { get; set; } = default!;
    }

    /// <summary>
    /// The `Status` type defines a logical error model.
    /// </summary>
    public class Error : SDKBaseException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public ErrorPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error.Payload.Message instead.")]
        private string? _message { get; set; }

        private static string ErrorMessage(ErrorPayload payload, string body)
        {
            string? message = payload.Message;
            if (!string.IsNullOrEmpty(message))
            {
                return message;
            }

            return "API error occurred";
        }

        public Error(
            ErrorPayload payload,
            HttpResponseMessage rawResponse,
            string body
        ): base(ErrorMessage(payload, body), rawResponse, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           _message = payload.Message;
           #pragma warning restore CS0618
        }
    }
}