name: Generate

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force the generation of the SDKs"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v15
    with:
      speakeasy_version: latest
      openapi_doc_location: https://docs.speakeasyapi.dev/openapi.yaml
      languages: |-
        - csharp
      publish_csharp: true
      force: ${{ github.event.inputs.force }}
      create_release: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
