name: Publish
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
on:
  workflow_dispatch:

jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    with:
      publish_csharp: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
